### ISSUE TITLE
Replace Cases Summary and Confirmed Cases dummy data with real data

### ISSUE THREAD

**Issue by ldtcooper** [sfbrigade/stop-covid19-sfbayarea#1]
We have SFDPH data on confirmed COVID-19 cases here: [covid_19_sf.txt](https://github.com/sfbrigade/stop-covid19-sfbayarea/files/4361156/covid_19_sf.txt)

The file is in `.txt` format so it could be uploaded here, but it's a CSV file with data on confirmed cases in San Francisco from 3/10-3/20.

This is the specific section:
<img width="1172" alt="Screen Shot 2020-03-20 at 10 59 06 AM" src="https://user-images.githubusercontent.com/24310179/77193071-df2d0980-6a9a-11ea-85a0-436d923b3539.png">

**Comment by kengoy** [comment]
I will do this.
