### ISSUE TITLE
Great to have Bart ride counts

### ISSUE THREAD

**Issue by kengoy** [sfbrigade/stop-covid19-sfbayarea#10]
The public transit ride counts is unfortunately impossible for the public (and even SFMTA) to get access to in real-time because BART (oddly) controls access to that data and doesn't release it via API. When this is all over, I hope the city can step in and force all local public transit agencies to produce ridership data in near real-time (at least daily) via API. 

https://www.bart.gov/about/reports/ridership

Here is the sample screen shot done by Tokyo govenment.
<img width="596" alt="Screen Shot 2020-03-22 at 8 47 49 PM" src="https://user-images.githubusercontent.com/61864097/77279177-68506600-6c7e-11ea-9eec-567145d0fac9.png">

**Comment by frhino** [comment]
They may be releasing data by flat file occasionally, but likely won't be making real time updates anytime soon.

**Comment by kengoy** [comment]
Won't do this. Will close.
