### ISSUE TITLE
Update Footer

### ISSUE THREAD

**Issue by justinjiangrws** [sfbrigade/stop-covid19-sfbayarea#105]
**Is your feature request related to a problem? Please describe.**
Update footer since we would like to include more content and links to direct people.

**Describe the solution you'd like**
Updated footers - preliminary designs have already been designed!

**Describe alternatives you've considered**
See attached:

![footer v2](https://user-images.githubusercontent.com/10675221/81245254-61c94400-8fc9-11ea-8f26-cad1781a98cb.png)

![mobile footer v2](https://user-images.githubusercontent.com/10675221/81245250-6130ad80-8fc9-11ea-8ef5-2015f1c1d615.png)

**Actionable Items**
Need signoff to hand off to developers.

**Comment by kengoy** [comment]
Hey @kkchu791 , here is the footer design UX team provided.  You can work to communicate with the UX team on this ticket.

For detail to see the CSS code, you can refer to the Figma, right panel select "Code".
https://www.figma.com/file/iUS5LdAnuTKVei88QwPPCH/Bay-Area-Pandemic-Dashboard-(PanDa)-by-Bay-Area-Brigades?node-id=602%3A127

For any questions about UI, ask @justinjiangrws.
For questions about current dev, ask @kengoy

**Comment by kengoy** [comment]
Hey @kkchu791 , just wanted to check out this status, and see if I can help this out to work together. I talked to @thuongho in today's hack night that he is also available to help. Please let me know your status. No worries about not making progress even if that's the case. We are the team to help out and learn together.

**Comment by kengoy** [comment]
We can close this now.
