### ISSUE TITLE
Add a link to the new BAPD Open Database

### ISSUE THREAD

**Issue by benghancock** [sfbrigade/stop-covid19-sfbayarea#1073]
I think it would be great if researchers and other interested, data-savvy members of the public could easily explore the COVID-19 data that this project has collected. Toward that goal, I've deployed a website using the Python `Datasette` library that allows users to view and query the data directly in the browser, and am hoping that a link can be added from the main site to what I've dubbed the "BAPD Open Database". 

Here are some details:
* The site is currently hosted on Heroku at https://sfbayarea-covid19db-test.herokuapp.com/ (the `-test` is in the subdomain just for now while this has been a WIP; I would drop that for production)
* The code to build and deploy the BAPD Open Database is [here](https://github.com/benghancock/covid19-sfbayarea-opendb)
* The data that populates this database is pulled directly from the `data.v2.json` file that lives in this repo. My plan for now is just to manually run the script that fetches the data and restructures it, and re-publish to the web every few days.

Here's some language that could be used on this site to explain what the link directs to:

> The BAPD Open Database gives researchers and other interested members of the public direct access to the data that Code for San Francisco has collected from local government web sites throughout the pandemic to build this dashboard. You can explore the data right in your web browser, write analytical queries in SQL, or download the data in a tidy, spreadsheet-friendly format.

Let me know what you think ~ Thanks!

**Comment by nikobooth** [comment]
Nice @benghancock , I've added designs for two ways for visitors to access this info, one on the about page and another in the banner CTA module on the stats page.

![about](https://user-images.githubusercontent.com/63436818/113230702-70a68e00-924e-11eb-9087-9be6f913b41a.png)

![data-v2](https://user-images.githubusercontent.com/63436818/113230710-743a1500-924e-11eb-9f37-91343409f6ba.png)

Note that the banner CTA for the FAQ and info pages should remain as is, just change the one for stats page.

**Comment by benghancock** [comment]
This looks so good @nikobooth ! Thanks for your work on this. I've added more of the data that we collect into a new table and republished the Open Database at this URL:

https://bapd-opendb.herokuapp.com

What's the next step to take this live?

**Comment by nikobooth** [comment]
Just need to see if anyone on the front end can pick it up, I'll ping in the FE channel
