### ISSUE TITLE
Great to have the number of people visiting a government office

### ISSUE THREAD

**Issue by kengoy** [sfbrigade/stop-covid19-sfbayarea#11]
The number of people visiting a government office, might be easier to start collecting? The question is, which offices are open to the public and how hard would it be to count them? It seemed like data people might find interesting if it were available. Metrics like this are more of a barometer people can keep an eye on to see how the situation is progressing more than as a critical data point.

Here is the sample screenshot created by Tokyo Government with Code for Japan.
<img width="670" alt="Screen Shot 2020-03-22 at 8 52 19 PM" src="https://user-images.githubusercontent.com/61864097/77279479-165c1000-6c7f-11ea-99c9-c48acd4d8139.png">

Comment by Jason Lally,
>  The second thing, number of people visiting government offices, that's a bit of a blindspot for me. I'm not sure what has been put in place to track that. I'll take a look at the underlying data and see if there's something that departments are already doing, but I'll have to ask

**Comment by frhino** [comment]
We probably won't get this data and I'm not sure if people in SF utilize government offices in the same way as in Japan, so maybe not as interesting as a datapoint here?
