### ISSUE TITLE
Fix css warnings 

### ISSUE THREAD

**Issue by kbrdsk** [sfbrigade/stop-covid19-sfbayarea#1166]
**Is your feature request related to a problem? Please describe.**
When running yarn dev there are three warnings that appear multiple times from the postcss-loader module
* Autoplacement does not work without grid-template-rows property
* start value has mixed support, consider using flex-start instead
* IE does not support align-items on grid containers. Try using align-self on child elements instead: .MainPage .DataBlock .county-select-container > * { align-self: center }

They're polluting the console a bit and it would be nice to have them resolved.

**Describe the solution you'd like**
Accept the suggestions in each warning.

**Describe alternatives you've considered**
I'm not sure if these warnings have been intentionally ignored and should be surpressed, feedback here would be appreciated if the person who originally wrote the css is around and has the space.

**Comment by frhino** [comment]
@kengoy are you free to take a look at this?

**Comment by kengoy** [comment]
Sorry for my late review. I have merged it. Thank you for cleaning up the codes and fixing the warnings. @kbrdsk
