### ISSUE TITLE
UI Design Update for more user-friendly experience 

### ISSUE THREAD

**Issue by kengoy** [sfbrigade/stop-covid19-sfbayarea#13]
Here is the design sample.

https://www.figma.com/file/iUS5LdAnuTKVei88QwPPCH/COVID-19-Tracker-by-Code-for-SF?node-id=0%3A1

**Comment by frhino** [comment]
Latest wireframes for integrateing FAQ with the original layout here: https://www.figma.com/file/iUS5LdAnuTKVei88QwPPCH/COVID-19-Tracker-by-Code-for-SF?node-id=602%3A128

**Comment by thuongho** [comment]
I'm working on the side menu.
