### ISSUE TITLE
Add chart for age/gender statistics

### ISSUE THREAD

**Issue by nikobooth** [sfbrigade/stop-covid19-sfbayarea#162]
**Once Stage 1 (County Selector) is live, we can add this chart**

We have age and gender information linked into our data model but currently do not display these on our site.

Screenshot and link to the Figma file:
![Age_Gender](https://user-images.githubusercontent.com/63436818/83457979-9092d880-a416-11ea-894d-47b0b62c452b.png)

https://www.figma.com/file/iUS5LdAnuTKVei88QwPPCH/Bay-Area-Pandemic-Dashboard-PanDa-by-Bay-Area-Brigades?node-id=1846%3A0

This chart should follow the Deaths by County chart. Refer to Stage 3 Mockup frame on Figma for the position of this chart within the county stats dashboard.

Info tooltip should read: "Age and gender data provided by California Health and Human Services"

Should consult the data scraping team for destination of 'open data source' link

**Comment by elaguerta** [comment]
We may want to provide the option of separating gender and age to make it easier to compare across counties. Gender groups should be relatively easy to compare across counties, but the age buckets are different. Here's a thought on using a color scale to compare age brackets across different counties. Note that I'm only showing absolute numbers - we probably want the colors to be assigned to percent of total cases. Ideally we would normalize with population totals from the census, but the age brackets don't match up with the census age brackets (!!!!). See attached excel file. 
[covid_age_viz.xlsx](https://github.com/sfbrigade/stop-covid19-sfbayarea/files/4719608/covid_age_viz.xlsx)


![image](https://user-images.githubusercontent.com/12928553/83567916-39a10800-a4d7-11ea-9b9e-78c7dc143b2b.png)

**Comment by nikobooth** [comment]
@thuongho here are the updated charts with gender and age separated!

![County Cases - Age](https://user-images.githubusercontent.com/63436818/86840242-5b9e2500-c057-11ea-8074-b61f3d1df8ec.png)

![County Cases - Gender](https://user-images.githubusercontent.com/63436818/86840299-6b1d6e00-c057-11ea-81e6-e151f9f8a4fb.png)

and here is the link to their Figma frames: https://www.figma.com/file/iUS5LdAnuTKVei88QwPPCH/Bay-Area-Pandemic-Dashboard-PanDa-by-Bay-Area-Brigades?node-id=2188%3A8697

Let me know any questions!

**Comment by thuongho** [comment]
Sweet! Thanks for the update @nikobooth. It looks good! If I run into any questions, I'll let you know.

**Comment by nikobooth** [comment]
Note to please adjust chart title: "Confirmed Cases by Sex: <County Name>"

**Comment by thuongho** [comment]
Age and Sex charts delivered with #259. Closing issue.
