### ISSUE TITLE
Create charts for Race & Ethnicity data

### ISSUE THREAD

**Issue by nikobooth** [sfbrigade/stop-covid19-sfbayarea#163]
**Once Stage 1 (County Selector) is live, we can add this chart**

Cases by Race & Ethnicity data has been linked up to our data model and we can create charts to display these statistics.

Screenshots:
 
![County Cases - Race Ethnicity](https://user-images.githubusercontent.com/63436818/83466285-79aab100-a42b-11ea-8e32-341f51698ffb.png)

![County Cases - Race Ethnicity per 1000](https://user-images.githubusercontent.com/63436818/83466296-8202ec00-a42b-11ea-9072-5304ee0604c2.png)

and link to the Figma file:
https://www.figma.com/file/iUS5LdAnuTKVei88QwPPCH/Bay-Area-Pandemic-Dashboard-PanDa-by-Bay-Area-Brigades?node-id=1846%3A0

These charts should follow the Cases by Age and Gender chart. Refer to Stage 3 Mockup frame on Figma for the position of this chart within the county stats dashboard.

To calculate cases per 1000 population, I used US census data from 2018 linked here: https://data.census.gov/cedsci/profile?g=0500000US06075&q=San%20Francisco%20County,%20California
This may be worth including in the tooltip for that chart.

Should consult the data scraping team for destination of 'open data source' link

**Comment by elaguerta** [comment]
In the data model, the field `source_url` should be the destination of the "open data source" link. 
Please also see the field `meta_from_baypd`, this text should be included in the "Data Notes."
In addition to citing "US Census Data", I would add that the source is the "2018 American Community Survey 5-Year Estimates".

**Comment by nikobooth** [comment]
For the per 1000 chart, I think we can keep the format as shown in the mockup above. For the population demographic data, I think the consensus was that the 2018 census data was fine to use in the method I described 2 weeks ago. Basically [ETHNICTY]POPULATION = [COUNTY]POPULATION*[ETHNICITY]%
for example:
![image](https://user-images.githubusercontent.com/63436818/88756585-e20acb80-d118-11ea-95b4-ddc609ac5c38.png)
[white]population = 870,044*0.467 = 406,310 people.

Then to do the cases per 1000 people, you use [ETHNICITY]CASES/([ETHNICITY]POPULATION/1000)
so again for white people:
557cases/(406,310/1,000) = 1.37 cases/1000 people

I've compiled the estimated population of each ethnicity in this sheet so you should just have to run the second equation with these numbers (as we're not going to get new population estimates any time soon).
https://docs.google.com/spreadsheets/d/1h8DtYYr4XWUpQw5jHU7MbJE6BW3WttnxeUcs184VsNs/edit?usp=sharing
