### ISSUE TITLE
Implement dynamic fetching data after API (or csv for bayarea) by #covid-data-fetch team is ready.

### ISSUE THREAD

**Issue by kengoy** [sfbrigade/stop-covid19-sfbayarea#21]
Until the API or CSV for bayarea is ready, we are updating manually by editing data/data.son.
Next step is to fetch data and build data.json dynamically.

Most likely the following Corona Data Scraper will be the master data source.
https://coronadatascraper.com/timeseries.csv
https://coronadatascraper.com/timeseries-byLocation.json

#covid-data-fetch @ldtcooper is working on preparing an API returning json for coutny level in the Bay Area.

**Comment by frhino** [comment]
@ldtcooper can this be closed?

**Comment by ldtcooper** [comment]
Yes!
