### ISSUE TITLE
Top Navigation Bar in About Page does not work as expected

### ISSUE THREAD

**Issue by kengoy** [sfbrigade/stop-covid19-sfbayarea#272]
The about page that the top nav bar doesn't work except to go back to the home page. Also it shows FAQ as being the currently selected section.

Need to adjust that no section is highlighted and that clicking 'faq', 'stats', or 'updates' will take users to the relevant section.

![87257887-c7b3cb00-c453-11ea-8552-5925124664ae](https://user-images.githubusercontent.com/61864097/87514979-fa1a1f80-c62f-11ea-9a34-98723ab31fcd.png)

**Comment by thuongho** [comment]
Fixed with #304
