### ISSUE TITLE
Update the "Latest Update" link to the current most important announcement link.

### ISSUE THREAD

**Issue by kengoy** [sfbrigade/stop-covid19-sfbayarea#3]
Related source code: components/WhatsNew.vue.

![Screen Shot 2020-03-21 at 3 34 01 PM](https://user-images.githubusercontent.com/61864097/77237973-c7807e80-6b89-11ea-9cbf-50bd5dcf2ac5.png)

**Comment by frhino** [comment]
@kengoy @ldtcooper Should this issue be moved to the data fetch repo?

**Comment by kengoy** [comment]
Close this.
