### ISSUE TITLE
Great to have Muni ride counts

### ISSUE THREAD

**Issue by kengoy** [sfbrigade/stop-covid19-sfbayarea#32]
Related to slack

https://sfbrigade.slack.com/archives/C7HUYBHAA/p1585247105015500

https://sfbrigade.slack.com/archives/C7HUYBHAA/p1553732281200000?thread_ts=1553732281.200000

https://www.sfmta.com/reports/percentage-muni-trips-service-gaps

**Comment by frhino** [comment]
Will re-label this issue if the data becomes available!

**Comment by kengoy** [comment]
Won't do this. will close.
