### ISSUE TITLE
Death number is not updated in each county chart if disable "Confirmed" 

### ISSUE THREAD

**Issue by kengoy** [sfbrigade/stop-covid19-sfbayarea#42]
**Describe the bug**
Only "Confirmed" cases number is shown in the header of each chart even the chart shows both "Confirmed" and "Deaths".
If user click "Confirmed" to disable "Confirmed" and to see only death chart, the above shown number should be updated for deaths number.

**To Reproduce**
1. Click on 'Confirmed' label on each chart
2. The chart shows only Death cases but the number above the chart still shows for Confirmed cases.

**Expected behavior**
The number above the chart should be updated if user only see death cases.

**Screenshots**

![Screen Shot 2020-04-05 at 11 44 09 PM](https://user-images.githubusercontent.com/61864097/78530160-015fa080-7798-11ea-81ac-191e1e701349.png)
![Screen Shot 2020-04-05 at 11 44 04 PM](https://user-images.githubusercontent.com/61864097/78530162-01f83700-7798-11ea-9fec-ff12410c9e3e.png)

**Comment by frhino** [comment]
@kengoy Shouldn't we have confirmed *and death* numbers above at all times? Here's a mock up kind of like that would look like:
![image](https://user-images.githubusercontent.com/7381521/78604090-d5d3c900-781e-11ea-8fbd-b51d1a40ba63.png)

**Comment by kengoy** [comment]
@frhino That's a good idea. I would need to change a data model for the view component but I think we should show that way.

**Comment by frhino** [comment]
I'm on with the UX team now and we'll discuss.

**Comment by kengoy** [comment]
The latest chat has separate charts between confirmed cases and deaths. This is no longer an issue. Let me close this.
