### ISSUE TITLE
Update the important links in the side menu.

### ISSUE THREAD

**Issue by kengoy** [sfbrigade/stop-covid19-sfbayarea#5]
Related source code: components/SideNavigation.vue

![Screen Shot 2020-03-21 at 3 34 21 PM](https://user-images.githubusercontent.com/61864097/77238021-31008d00-6b8a-11ea-87ce-02488366ada5.png)

**Comment by frhino** [comment]
@kengoy Do you think we should have a repo for the FAQ work, or could we just assign issues either here or in the data fetch repo (I lean to data fetch)? We have a need for people to assign themselves to categories and regions, and the general info could use that same attention.

**Comment by kengoy** [comment]
Design has been changed already. Will close this as this is no longer an issue.
