### ISSUE TITLE
Add a share widget to the data dashboard page

### ISSUE THREAD

**Issue by frhino** [sfbrigade/stop-covid19-sfbayarea#519]
to drive more social shares
We can typically find a plugin or a JS snippet to complete this

**Comment by nikobooth** [comment]
@thomhammond I'm thinking we float the widget at the bottom for mobile view and on the top right side for desktop views, here's what it would look like on our main page views for mobile:

<img width="414" alt="landing-v2" src="https://user-images.githubusercontent.com/63436818/99734273-5de9a480-2a77-11eb-887b-ddd0fda96b59.png">

<img width="414" alt="faq-v2" src="https://user-images.githubusercontent.com/63436818/99734287-6346ef00-2a77-11eb-8eb6-0a51d139bf2c.png">

<img width="414" alt="data-v2" src="https://user-images.githubusercontent.com/63436818/99734292-6641df80-2a77-11eb-80d4-b8c189d7ff8e.png">

<img width="414" alt="updates-v2" src="https://user-images.githubusercontent.com/63436818/99734295-68a43980-2a77-11eb-90b2-653971a6a729.png">

...and desktop:

<img width="1408" alt="faq-v2" src="https://user-images.githubusercontent.com/63436818/99734835-5bd41580-2a78-11eb-8afe-d070395d1592.png">

In all instances, it should pin to that screen location (following users as they scroll). The fifth option there (with the 'share' icon) can open up the default system share options on mobile (which will include text, email, other installed messaging platforms). On desktop, I'm not sure if we have to specify which options will be in there, if so - maybe just add email as an option?

If making them round on desktop while rectangular on mobile is too much of a pain, stacked squares for the desktop version would work just as well. Let me know any questions here or on Slack!

**Comment by thomhammond** [comment]
Awesome, thanks! I hope to have some time to dig in this weekend. Just to double-check, the icons should stick on desktop as well? Just want to make sure I didn't misunderstand that!

**Comment by nikobooth** [comment]
Yup, they'll follow the user as they scroll. If we find later that they're not being used too much, we can find a static home for them somewhere.

**Comment by nikobooth** [comment]
@thomhammond I think the simplest solution for the share widget will be just have them be static on the banner at top. The gains from having them follow the user but collapse if they interfere are marginal so lets go with the easier implementation. For the landing page, we can bottom align them with the three main CTAs

![landing-v2](https://user-images.githubusercontent.com/63436818/104151061-d3476680-5390-11eb-84dc-6824969b66af.png)

**Comment by nikobooth** [comment]
@thomhammond one last thing on this issue, can we set a minimum padding between the share widget and the "help us raise awareness" module? Right now they overlap in certain screen widths.

![image](https://user-images.githubusercontent.com/63436818/106083383-46f7ac00-60d1-11eb-845b-133eaf216517.png)

This screen shot was taken with my screen width at ~1300, once this is done I figure we can close this issue!

**Comment by thomhammond** [comment]
> @thomhammond one last thing on this issue, can we set a minimum padding between the share widget and the "help us raise awareness" module? Right now they overlap in certain screen widths.

> This screen shot was taken with my screen width at ~1300, once this is done I figure we can close this issue!

Sounds good. I have to run tonight but I will take a look tomorrow!
