### ISSUE TITLE
Prototype

### ISSUE THREAD

**Issue by kmkimbro** [sfbrigade/stop-covid19-sfbayarea#57]
**Is your feature request related to a problem? Please describe.**
As a final deliverable, UX/UI team needs to create a prototype for the developers so they can implement the design.

**Describe the solution you'd like**
Principle or figma. 

**Describe alternatives you've considered**

**Additional context**

**Comment by frhino** [comment]
@kmkimbro Is this issue for a prototype of the whole website, any prototype in the future, or a prototype to help communicate a specific UI? (any is ok!) 

- If for a prototype of the whole website, I think we might need to break it down into multiple other issues
- If for any prototype in the future, then we might consider making a new New Issue Template for UX team so they remember to deliver all the assets necessary to the web dev team. 
- If it's for a specific UI, then a couple more words in the title would be good as well as more specifics in the description.

**Comment by kengoy** [comment]
@kmkimbro @justinjiangrws  Can you attach the landing image (gg bridge with purple background)? I can see other stylesheet and icons in #55.

**Comment by justinjiangrws** [comment]
@kengoy Let me know if this works. There are 3 resolutions attached. Should there be a folder for digital assets on the github? (or is there one already?)

![header-bg](https://user-images.githubusercontent.com/10675221/79512486-61571200-7ff6-11ea-8c7b-f71946a711fa.png)
<img width="1440" alt="header-bg@2x" src="https://user-images.githubusercontent.com/10675221/79512494-64520280-7ff6-11ea-9c74-6f45e17c23cf.png">
![header-bg@3x](https://user-images.githubusercontent.com/10675221/79512497-65832f80-7ff6-11ea-9f67-cc5fc2629184.png)

**Comment by kengoy** [comment]
@justinjiangrws That works! Thank you. I can add this on the github when I finish the development. No worries.

**Comment by kengoy** [comment]
Hey @justinjiangrws, I have a few questions/requests.

- What's the font do we use on this design? Is it available somewhere like google font?
- Is it possible to provide a png file for the following icon on the header? It would be great if you could provide two versions, one is just for icon and another is icon plus text next to it. 

![header-icon-wtext](https://user-images.githubusercontent.com/61864097/80429453-faace080-88a0-11ea-89f5-04577dfcb386.png)
![header-icon](https://user-images.githubusercontent.com/61864097/80429455-fb457700-88a0-11ea-85f9-85a6bdd1230b.png)

**Comment by kengoy** [comment]
Here is the working-in-progress site FYI.
https://panda.baybrigades.org/

**Comment by justinjiangrws** [comment]
Hey @kengoy - the font style is on the stylesheet, towards the bottom of the **01. Type** section. I've attached a screenshot in case you need to refer to it:

<img width="300" alt="Screen Shot 2020-04-27 at 4 21 43 PM" src="https://user-images.githubusercontent.com/10675221/80430414-65f7b200-88a3-11ea-9274-14a16828a7f7.png">

Also, I've created the logo styles in the **05. Icons** section of the stylesheet. Thanks for the reminder!

Here's the zipped file: [icon styles.zip](https://github.com/sfbrigade/stop-covid19-sfbayarea/files/4542574/icon.styles.zip)

In the future, you should be able to access the exportable files by checking the Figma file and exporting them from there.

<img width="218" alt="Screen Shot 2020-04-27 at 4 41 52 PM" src="https://user-images.githubusercontent.com/10675221/80431923-a3f6d500-88a7-11ea-838e-9468b6f8ae25.png">
<img width="579" alt="Screen Shot 2020-04-27 at 4 43 34 PM" src="https://user-images.githubusercontent.com/10675221/80431925-a5280200-88a7-11ea-8e63-c27af4731010.png">

Let me know if I've missed anything!

**Comment by kengoy** [comment]
Thanks, @justinjiangrws ! Perfect. I was not aware of the exporting way on the figma so I can do that next time.

As for the font SF Pro, it looks like it's against Apple's policy to use it for other than Apple devices (iOS, macOS, tvOS, etc). So I applied the font-family as follows. This way works SF Pro on the apple device and alternative font will be used on non-apple device (Windows, Android etc)
```
* {
  font-family: -apple-system, BlinkMacSystemFont, sans-serif;
}
```

**Comment by justinjiangrws** [comment]
Oh wow. That was not something I was aware of. I mainly chose it as an homage to the Bay Area.

I'll find an alternative font type to use - I would like for the site to be device agnostic.
