### ISSUE TITLE
Keep up-to-date number in data.json until automatic fetch data via API will be developed. 

### ISSUE THREAD

**Issue by kengoy** [sfbrigade/stop-covid19-sfbayarea#6]
Related source code: data/data.json.

Steps:
1. Git clone https://github.com/sfbrigade/data-covid19-sfbayarea/tree/corona-scraper on your local.
2. Follow the instruction of installation and run the scraper.py . 
```
 $ sh run_scraper.sh > data.json
  or
 $ python3 scraper.py > data.json
```
3. Copy the generated data.json to data/data.json
4. Confirm if it works on your local before commit.
5. Git commit & push

**Comment by ldtcooper** [comment]
Do we need an API in the data project to get this?

**Comment by kengoy** [comment]
That would be great! I think many people who want to visualize the data for the local county/city are looking for API to be prepared.  For the stop-covid19-sfbayarea, I think I can fetch the csv file directly parse it directly.

**Comment by frhino** [comment]
@kengoy   What is the status here? Should we create an issue for automation?

**Comment by kengoy** [comment]
GitHub Action is ready. Close this.
