### ISSUE TITLE
UI Design Update based on the wireframe and style sheet.

### ISSUE THREAD

**Issue by kengoy** [sfbrigade/stop-covid19-sfbayarea#63]
UX team provided UI wireframe and style sheet #55 #57 .

This ticket is for development.

**Comment by kengoy** [comment]
Completed Sub-tasks:
- Create/Layout the top page (default.vue)
- Create tab page (main.vue)
- Add an app toolbar (main.vue)
- Add 3 tabs (FAQ, Status, News)
- Add components to each FAQ, Status, News
- Link from the top page and tab page


Remaining Sub-tasks:
- Link to each tab in the tab page from each card on the top page.
- Style/Font change:
- Link from tab page to back to the top page
- Layout issue on the tab page (app toolbar sometimes breaks the layout)
- Add side navigation in the main page (@thuongho)

**Comment by kengoy** [comment]
Hey @thuongho, I am still working on this design change task. But if you could have a chance to look the branch "feature/issue63", I think you can work on your side navigation task for the main.vue I have re-factored for the new design. Please let me know if you have any questions.

**Comment by thuongho** [comment]
@kengoy cool. Looking good!

**Comment by kengoy** [comment]
Completed Sub-tasks:
- Link to each tab in the tab page from each card on the top page.
- Style/Font change:
- Link from tab page to back to the top page
- Layout issue on the tab page (app toolbar sometimes breaks the layout)

Remaining Sub-tasks:
- Update logo and language based on the latest design with the decided site name (Bay Area PanDa)
- Add side navigation in the main page (@thuongho)

**Comment by justinjiangrws** [comment]
Hey @kengoy is there any particular reason why the logos on the website are blurry? Is it because you are using a .png to display them?

<img width="1280" alt="Screen Shot 2020-05-05 at 10 43 15 AM" src="https://user-images.githubusercontent.com/10675221/81098018-9a7bf700-8ebd-11ea-85ab-d8de377c14c7.png">

<img width="1280" alt="Screen Shot 2020-05-05 at 10 41 21 AM" src="https://user-images.githubusercontent.com/10675221/81098020-9cde5100-8ebd-11ea-9e22-708c824bef57.png">

I can give you a higher-res logo image (or maybe it's too high res), but are you able to use text to display the rest of it (the part that says "Covid-19 Tracker, by Code for San Francisco)?

**Comment by kengoy** [comment]
Hey @justinjiangrws, thanks for catching. I just exported from figma to a ping file and show it as it is. Here is the exported png file. 
![header-icon-wtext](https://user-images.githubusercontent.com/61864097/81110921-159ad880-8ed1-11ea-966e-67951aed3016.png)

But I think I better use text for the next part to align with other text fonts as you suggested. I was just lazy to adjust the two lines layout next to the logo image, and put all together as a link to the top page. That's why I used the exported png. I will change it to text :)

**Comment by kengoy** [comment]
Hey @justinjiangrws, I made changes to the logo. Please check and feel free to share if it looks okay as expected.
https://panda.baybrigades.org/main

**Comment by justinjiangrws** [comment]
Thanks for tackling the issue @kengoy! 

I'm seeing the changes reflected on the navigation bar but not on the landing page. However, I'm also having issues with the navigation bar and for me it's not appearing as expected:

<img width="281" alt="Screen Shot 2020-05-06 at 4 40 55 PM" src="https://user-images.githubusercontent.com/10675221/81239146-da73d480-8fb8-11ea-9474-b99be6184ec0.png">

**Comment by kengoy** [comment]
I made a fix. Can you please confirm the layout issue again? @justinjiangrws 
I also made changes on the landing page so that the logo text should be clearly rendered.

What's the issue with the navigation bar for you? Can I get the screenshot you are seeing?

**Comment by justinjiangrws** [comment]
Okay I see the fix! Think the landing page is good (as far as the logo is concerned). What do you mean by layout issue? @kengoy 

As far as the landing page, here is my screenshot:

<img width="1280" alt="Screen Shot 2020-05-11 at 10 39 51 AM" src="https://user-images.githubusercontent.com/10675221/81596403-e07f0200-9378-11ea-9d5a-907942ebd59b.png">

The overflow has been fixed, but now it's cutting off text.

**Comment by kengoy** [comment]
@justinjiangrws  I don't see the ending "r"  on your screenshot if my eys is normal...  Let me fix it.

I meant the layout issue is below.

> However, I'm also having issues with the navigation bar and for me it's not appearing as expected:

**Comment by kengoy** [comment]
I made a fix for the cutting off text issue. Fingers crossed. @justinjiangrws

**Comment by kengoy** [comment]
No remaining issues for this ticket. I will close.
