### ISSUE TITLE
Automate news feed for San Francisco

### ISSUE THREAD

**Issue by Mr0grog** [sfbrigade/stop-covid19-sfbayarea#68]
On the news screen, we show news items from San Francisco’s official COVID news page (https://sf.gov/news/topics/794). However, we are currently populating this info by hand!

Instead, we should have a script (that we can later automate with `cron` or a CI job) that pulls down all the news items and adds them to [`data/news.json`](https://github.com/sfbrigade/stop-covid19-sfbayarea/blob/master/data/news.json).

**Comment by Mr0grog** [comment]
The city’s new site does not appear to have an RSS or Atom feed, so we may have to scrape the news page. :(

(I’ve also sent a bit in the new website feedback form about this, so with any luck they’ll add one — or just point out whatever I missed.)

**Comment by Mr0grog** [comment]
Per discussion in Slack, the code for this has moved over to the data repo at: https://github.com/sfbrigade/data-covid19-sfbayarea/pull/35

**Comment by kengoy** [comment]
@Mr0grog Thank you for your work on creating a scraper for the SF news. It would be great if you could help to update news.json in this repo using the script, at least until the automation like GitHub Action is available.

**Comment by Mr0grog** [comment]
Can do. Is there a time you regularly deploy, so I can make sure I do it beforehand?

**Comment by Mr0grog** [comment]
Posted a PR for the first update because it includes a small code change: #79.

Will post future updates that just touch the `news.json` file directly to master.

**Comment by Mr0grog** [comment]
This was fixed in 7af9b49062260cf5e8726ad2457e1609d6fa61c1
