### ISSUE TITLE
Rework Top Nav to Include Changes to name (Pandemic Dashboard)

### ISSUE THREAD

**Issue by justinjiangrws** [sfbrigade/stop-covid19-sfbayarea#71]
**Is your feature request related to a problem? Please describe.**

We've changed our name and scope of the Bay Area team.

**Describe the solution you'd like**

Quick changes to the top nav to read "Bay Area Pandemic Dashboard by Bay Area Brigades.

![top-nav](https://user-images.githubusercontent.com/10675221/80319950-26a86300-87c8-11ea-80c9-847d72a59b92.png)

**Additional context**

None

**Comment by kengoy** [comment]
This ticket is ready for development. Looking for a developer who can work on.

**Comment by thuongho** [comment]
Issue fixed and merged with PR#133. Closing issue.
