### ISSUE TITLE
Add a side navigation bar to the "County Info" page

### ISSUE THREAD

**Issue by MosesSupposes** [sfbrigade/stop-covid19-sfbayarea#750]
**Is your feature request related to a problem? Please describe.**
Currently, there is a sidebar for the "FAQ" tab that allows you to navigate between the different sections of the page, but there is no sidebar for the "County Info" tab.

**Describe the solution you'd like**
There should be a sidebar navigation on the "County Info" page.

**Describe alternatives you've considered**
N/A

**Additional context**
The component to edit is in the "News.vue" file under the components folder.

**Comment by kbrdsk** [comment]
@MosesSupposes Sorry! I misread you being assigned to this issue as you just having created it.

**Comment by MosesSupposes** [comment]
> @MosesSupposes Sorry! I misread you being assigned to this issue as you just having created it. 

@kbrdsk No worries! You beat me to it, so we might as well merge your PR. Great job!

**Comment by kbrdsk** [comment]
> > @MosesSupposes Sorry! I misread you being assigned to this issue as you just having created it.
> 
> @kbrdsk No worries! You beat me to it, so we might as well merge your PR. Great job!

@MosesSupposes Alright, also happy to restructure it around any ideas you have, I noticed you were the assignee because I was looking to request you for a review.

**Comment by MosesSupposes** [comment]
> > > @MosesSupposes Sorry! I misread you being assigned to this issue as you just having created it.
> 
> > 
> 
> > @kbrdsk No worries! You beat me to it, so we might as well merge your PR. Great job!
> 
> 
> 
> @MosesSupposes Alright, also happy to restructure it around any ideas you have, I noticed you were the assignee because I was looking to request you for a review.

I'll give it a look when I get off work in a few hours. From the quick skim I gave it earlier, it looks solid.

**Comment by thuongho** [comment]
closing as it was solved with #809
