### ISSUE TITLE
Small fixes for county age charts

### ISSUE THREAD

**Issue by nikobooth** [sfbrigade/stop-covid19-sfbayarea#822]
Some oddities and small fixes on the age chart:
1) For some counties there are mystery values. See SF for example, there is a mystery bar between 50-59 and 60-69.
2) Not all bars have labels. Labels should be visible for each bar on this chart.
2a) If we cannot add labels to all bars, the hover tip should be changed to add a bar label (see example below)

![image](https://user-images.githubusercontent.com/63436818/103971900-9b39ec80-5120-11eb-85b4-069feb3f3452.png)

**Comment by nikobooth** [comment]
One more thing! 3. Update Chart name to read "_Confirmed_ Cases by Age: xxxx County"

**Comment by yetesh** [comment]
Added #843

**Comment by thuongho** [comment]
@nikobooth I just merged @yetesh's fix with PR #843 into master. If it looks good to you, feel free to close this issue. Thanks guys!

**Comment by nikobooth** [comment]
Thanks @yetesh & @thuongho looks good!
