### ISSUE TITLE
Small fixes for county ethnicity charts

### ISSUE THREAD

**Issue by nikobooth** [sfbrigade/stop-covid19-sfbayarea#827]
General Fixes:
Remove "unknown" as a category from cases per 1000 chart.
Cases per 1000 chart should be reordered to show largest bar on the top, smallest on the bottom.
![image](https://user-images.githubusercontent.com/63436818/104055557-d7faf780-51a3-11eb-90eb-6353a2182147.png)

Some unintended characters appear in the top left corner of the chart
![image](https://user-images.githubusercontent.com/63436818/104055660-01b41e80-51a4-11eb-83ed-51efe430d250.png)

Alameda County shows 0 value for Hispanic & Black cases per 1000 despite cases existing:
![image](https://user-images.githubusercontent.com/63436818/104055395-95391f80-51a3-11eb-9dfe-49b654aac8a3.png)

Labelling Issues:
Solano County shows a category labeled "Total RE"
Alameda and San Mateo have a typo "Native Americanican"

**Comment by yetesh** [comment]
I'm working on this!

**Comment by thuongho** [comment]
@nikobooth should we change the title to `Confirmed` Cases?

<img width="733" alt="Screen Shot 2021-01-20 at 9 47 02 AM" src="https://user-images.githubusercontent.com/5452152/105214336-ba635180-5b04-11eb-9acd-d5b43ba1b9d4.png">

Seems like we have some negative data. @kengoy should we fix this at the data level or add a conditional check to not display negative data in the charts?

**Comment by nikobooth** [comment]
@thuongho yes! lets change it to "confirmed cases" thanks!

**Comment by kengoy** [comment]
> Seems like we have some negative data. @kengoy should we fix this at the data level or add a conditional check to not display negative data in the charts?

Hmm, it should be fixed in the original data scraped from the Santa Clara County site. But I agree to having a conditional check to not display negative data in the charts.

**Comment by yetesh** [comment]
Added #874
