### ISSUE TITLE
Updates to ICU chart

### ISSUE THREAD

**Issue by nikobooth** [sfbrigade/stop-covid19-sfbayarea#907]
To make the filtering affordance clearer on the ICU chart, let's follow the button pattern from our comparative charts:

![image](https://user-images.githubusercontent.com/63436818/106206140-714e7580-6174-11eb-91bd-03fe6bf5d5b7.png)

![image](https://user-images.githubusercontent.com/63436818/106206359-c8544a80-6174-11eb-987e-8e68e6504f00.png)

Note also that I've added the current % in the top right. Here is the link to the relevant frames in Figma: https://www.figma.com/file/iUS5LdAnuTKVei88QwPPCH/Bay-Area-Pandemic-Dashboard-PanDa-by-Bay-Area-Brigades?node-id=2989%3A9

The info tab should read:
"**what this graph shows** - This graph shows the ICU capacity and number of COVID ICU patients in the selected county. Use the control buttons to toggle each metric on or off."

Please feel free to suggest any edits to this in the comments

**Comment by kbrdsk** [comment]
Awesome! Thanks for doing the mockup!

**Comment by benghancock** [comment]
This looks great @nikobooth! As far as the info tab, we may want to add/clarify a bit. Perhaps something to this effect?

> This graph shows the number of suspected and confirmed COVID ICU patients, and the number of available ICU beds (including neonatal, pediatric, and adult ICU) in the selected county. Use the control buttons to toggle each metric on or off."

Maybe that's too long? Basing the description off of the [data dictionary](https://data.ca.gov/dataset/covid-19-hospital-data/resource/42d33765-20fd-44b8-a978-b083b7542225) for this timeseries.

One question: How are we calculating the percentage? We have the metric `icu_available_beds`, which I interpret as the number of available beds on the given date, but I'm not sure we know the total ICU beds for a given county. If we do this:

``` text
icu_available_beds / (icu_available_beds + icu_suspected_covid_patients + icu_confirmed_covid_patients)
```
... that might be a rough proxy, but of course wouldn't take into account non-COVID ICU patients. I might just be missing something though.

**Comment by kbrdsk** [comment]
> This looks great @nikobooth! As far as the info tab, we may want to add/clarify a bit. Perhaps something to this effect?
> 
> > This graph shows the number of suspected and confirmed COVID ICU patients, and the number of available ICU beds (including neonatal, pediatric, and adult ICU) in the selected county. Use the control buttons to toggle each metric on or off."
> 
> Maybe that's too long? Basing the description off of the [data dictionary](https://data.ca.gov/dataset/covid-19-hospital-data/resource/42d33765-20fd-44b8-a978-b083b7542225) for this timeseries.
> 

I really like what you added to the description here.

> One question: How are we calculating the percentage? We have the metric `icu_available_beds`, which I interpret as the number of available beds on the given date, but I'm not sure we know the total ICU beds for a given county. If we do this:
> 
> ```
> icu_available_beds / (icu_available_beds + icu_suspected_covid_patients + icu_confirmed_covid_patients)
> ```
> 
> ... that might be a rough proxy, but of course wouldn't take into account non-COVID ICU patients.

I mentioned [data.sfgov.org](https://data.sfgov.org/stories/s/Hospital-Capacity/qtdt-yqr2/) in the PR as well but according to what's there almost 75% of ICU patients are non-COVID ones. I think if we show capacity we need to have it be (available ICU beds)/(total ICU beds).

**Comment by nikobooth** [comment]
Agree, Ben's text is excellent. +1 for using that!

Also good callout that we do not have an actual % of beds available. Let's leave that top right space blank for now.
