### ISSUE TITLE
Convert 14 day average to 7 day average with 7 day delay & revise 9 County Summary

### ISSUE THREAD

**Issue by nikobooth** [sfbrigade/stop-covid19-sfbayarea#986]
Currently, our standard is to average per 100k case numbers over a 14 day period. This appears in the first summary segment:
![image](https://user-images.githubusercontent.com/63436818/109877676-28cd2080-7c28-11eb-963f-7d18583a1a7b.png)

... and in our comparative charts:
![image](https://user-images.githubusercontent.com/63436818/109877725-371b3c80-7c28-11eb-9e75-099b1f649a4f.png)

County tier assignments rely on a 7 day average with a 7 day lag:
![image](https://user-images.githubusercontent.com/63436818/109886962-caa73a00-7c35-11eb-83ca-91f376803d29.png)

1) To better reflect how the data we collect impacts people's day to day lives, we should amend our formulae and visualizations to show the 7 day average with 7 day lag. 

In case there are any questions on how we should calculate this: If we wanted to show today's value (for 3/3) we would average the values for cases/100k from 2/18-2/24.

2) Additionally, the info overlay for the comparative graph should be adjusted to read:

> **What this graph shows**
> The daily values shown on this graph are the 7 day rolling average for the number of new cases with a one-week delay. This is one of the primary metrics for determining county tier assignments which directly affect which safety restrictions are in place.
>  
> **Why cases per 100,000?**
> Showing a population-adjusted value puts differently-sized counties on the same scale and allows for more accurate comparison.
> 
> **Why a 7 day average?**
>  Showing an average value smooths the data curve and makes trends easier to observe.

3) Finally, a few small changes should be made to the 9 County Summary bar. In the sub-statistic for cases, %growth is less relevant as the pandemic has dragged on and daily cases make up a less and less significant number. Therefore, replacing %growth with new daily cases holds more value for visitors.

Similarly, the death rate calculation is misleading because the number of known cases likely varies significantly from the number of actual cases. This can also be replaced with a daily total from the previous day.

Screenshots for these design changes are below and can also be found at: https://www.figma.com/file/iUS5LdAnuTKVei88QwPPCH/Bay-Area-Pandemic-Dashboard-PanDa-by-Bay-Area-Brigades?node-id=2974%3A9037

![Topline Summary](https://user-images.githubusercontent.com/63436818/109887804-45bd2000-7c37-11eb-895e-d3ced2315b93.png)

![100k line graph](https://user-images.githubusercontent.com/63436818/109887815-4bb30100-7c37-11eb-801f-9a62ae18fea1.png)

![100k line graph w overlay](https://user-images.githubusercontent.com/63436818/109887825-5077b500-7c37-11eb-986c-bd1f9a773ae2.png)

**Comment by thuongho** [comment]
Fix merged in #994. Closing.
