### ISSUE TITLE
Enhancements to comparative graph - Cases per 100k

### ISSUE THREAD

**Issue by nikobooth** [sfbrigade/stop-covid19-sfbayarea#987]
Note, this Issue is dependent on Issue #986 being completed first.

Requesting a few enhancements to the comparative cases per 100k chart:

1) Adding a "Bay Area Average" line. Theme color for this line can be dark grey/black (2D2D2D). Note that while the San Mateo scraper is still down, we shouldn't include it in the average calculation.

2) Add a "Tier Benchmarks" overlay option which will show how current levels correlate with county blueprint tiers. Additionally, adding a short description within the control panel where visitors can find additional information about county benchmarks. 
Link this to: https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/COVID-19/COVID19CountyMonitoringOverview.aspx

![Comparison controls](https://user-images.githubusercontent.com/63436818/109890576-5d4ad780-7c3c-11eb-9cb3-dd40bd719421.png)

![100k line graph](https://user-images.githubusercontent.com/63436818/109890587-6176f500-7c3c-11eb-8bc5-f9e95c5fc45f.png)

Note the positioning of the benchmarks are:
0-1 - Yellow
1-4 - Orange
4-7 - Red
7+ Purple

Link to Figma designs: https://www.figma.com/file/iUS5LdAnuTKVei88QwPPCH/Bay-Area-Pandemic-Dashboard-PanDa-by-Bay-Area-Brigades?node-id=3053%3A9037

**Comment by kbrdsk** [comment]
I think I can do this later this week
